# -*- coding: utf-8 -*-
"""code_pookalam entry.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SWvXgn5456R3Dwod4wlG_UeKfL-tJVyi
"""

pip install python-joy

from joy import *

MAROON = "#B71C1C"
ORANGE = "#FF6F00"
YELLOW = "#FFEB3B"
LIGHT_YELLOW = "#FFF59D"
GREEN  = "#1B5E20"
WHITE  = "#FFFFFF"
BROWN  =  "#562C2C"
BG_COLOR = "#EFECE6"
PURPLE = "#880E4F"
background = rectangle(w=300, h=300, fill=BG_COLOR, stroke="none")
show(background)

def diya():
    outer=circle(y=-145,r=14,fill=GREEN,stroke="none")
    ring=circle(y=-145,r=11,fill=YELLOW,stroke="none")
    inner=circle(y=-145,r=8,fill=MAROON,stroke="none")
    flame=ellipse(y=-163,w=7,h=16,fill=YELLOW,stroke="none")
    flame2=ellipse(y=-161,w=3.5,h=11,fill=ORANGE,stroke="none")
    return outer+ring+inner+flame+flame2

diyas=diya()|repeat(8,rotate(45))
show(diyas)

green_circle = circle(r=145, fill=GREEN, stroke="none")
show(green_circle)

def outer_circle():
  p1 = circle(y=140, r=4.5, fill=YELLOW, stroke="none")
  p2 = circle(y=140, r=1.5, fill=MAROON, stroke="none")
  return p1 + p2
outer_ring = outer_circle()  |repeat(36, rotate(10))
show(outer_ring)

def outer_circle1():
  p1 = circle(y=140, r=4.5, fill=MAROON, stroke="none")
  p2 = circle(y=140, r=1.5, fill=YELLOW, stroke="none")
  return p1 + p2
outer_ring1 = outer_circle1() |rotate(10) | repeat(18, rotate(20))
show(outer_ring1)

white_ring = circle(r=135, fill=WHITE, stroke="none")
brown_ring = circle(r=130, fill=BROWN, stroke="none")
yellow_ring = circle(r=128, fill=YELLOW, stroke="none")
inner=white_ring+brown_ring+yellow_ring
show(inner)

def flower_border():
    layer1 = circle(y=100, r=25, fill=MAROON, stroke="none")
    layer2 = circle(y=98, r=22, fill=ORANGE, stroke="none")
    layer3 = circle(y=96, r=18, fill=YELLOW, stroke="none")
    layer4 = circle(y=94, r=14, fill=LIGHT_YELLOW, stroke="none")
    return layer1 + layer2 + layer3 + layer4
outer_layer = flower_border() | repeat(16, rotate(22.5))
show(outer_layer)

yellow_ring = circle(r=92, fill=YELLOW, stroke="none")
show(yellow_ring)

layer1 = circle(y=72, r=25, fill=MAROON, stroke="none")|rotate(20) |repeat(8, rotate(45))
show(layer1)

inner_rectangle=rectangle(w=143,h=143,fill=PURPLE,stroke=BROWN)
show(inner_rectangle)

inner_rectangle1=rectangle(w=143,h=143,fill=PURPLE,stroke=BROWN) | rotate(45)
show(inner_rectangle1)

octagon1=polygon(points=[point(0,-82),point(58,-58),point(82,0),point(58,58),point(0,82),point(-58,58),point(-82,0),point(-58,-58)],fill=WHITE,stroke="none")|rotate(25)
inner_octagon=polygon(points=[point(0,-78),point(55,-55),point(78,0),point(55,55),point(0,78),point(-55,55),point(-78,0),point(-55,-55)],fill=YELLOW,stroke="none")|rotate(25)
octagon=octagon1+inner_octagon
show(octagon)

def large_petal():
  outer_p = ellipse(y=60, w=28, h=45, fill=MAROON, stroke="none")
  mid_p   = ellipse(y=58, w=22, h=38, fill=ORANGE, stroke="none")
  inner_p = ellipse(y=56, w=16, h=30, fill=YELLOW, stroke="none")
  core_p  = ellipse(y=54, w=10, h=20, fill=WHITE, stroke="none")
  return outer_p + mid_p + inner_p + core_p
large = large_petal() | repeat(8, rotate(45))
show(large)

center_green = circle(r=70,fill=GREEN,stroke="none")
show(center_green)

rectangle1=rectangle(w=115,h=80,fill=MAROON,stroke="none")|repeat(8,rotate(45))
show(rectangle1)

rectangle2=rectangle(w=110,h=80,fill=ORANGE,stroke="none")|rotate(15)|repeat(8,rotate(45))
show(rectangle2)

rectangle3=rectangle(w=105,h=80,fill=YELLOW,stroke="none")|rotate(20)|repeat(8,rotate(45))
show(rectangle3)

rectangle4=rectangle(w=100,h=80,fill=LIGHT_YELLOW,stroke="none")|rotate(20)|repeat(8,rotate(45))
show(rectangle4)

rectangle5=rectangle(w=95,h=80,fill=MAROON,stroke="none")|rotate(30)|repeat(8,rotate(45))
show(rectangle5)

from typing_extensions import OrderedDict
rectangle6=rectangle(w=90,h=80,fill=ORANGE,stroke="none")|rotate(40)|repeat(8,rotate(45))
show(rectangle6)

rectangle7=rectangle(w=85,h=80,fill=YELLOW,stroke="none")|rotate(50)|repeat(8,rotate(45))
show(rectangle7)

rectangle8=rectangle(w=90,h=80,fill=LIGHT_YELLOW,stroke="none")|rotate(50)|repeat(8,rotate(45))
show(rectangle8)

r1=rectangle(w=90,h=50,fill=PURPLE,stroke="MAROON") | repeat(72,rotate(10) |scale(0.9))
r2=rectangle(w=50,h=90,fill=PURPLE,stroke="MAROON") | repeat(72,rotate(10) |scale(0.9))
r=r1+r2
show(r)

outter=circle(r=22,fill=MAROON,stroke="none")+circle(r=20,fill=GREEN,stroke="none")
lines1=(rectangle(y=15,w=5,h=16,fill=MAROON,stroke="none")+rectangle(y=15,w=5,h=16,fill=MAROON,stroke="none"))|repeat(8,rotate(45))
lines2=(rectangle(y=15,w=5,h=16,fill=WHITE,stroke="none")+rectangle(y=15,w=5,h=16,fill=MAROON,stroke="none"))|repeat(8,rotate(45))
octagon=polygon([point(0,-22),point(16,-16),point(22,0),point(16,16),point(0,22),point(-16,16),point(-22,0),point(-16,-16)],fill=WHITE,stroke="none")
def small_petal():
    outer_p=ellipse(y=16,w=6,h=11,fill=MAROON,stroke="none")
    mid_p=ellipse(y=15,w=5,h=9,fill=ORANGE,stroke="none")
    inner_p=ellipse(y=14,w=4,h=7,fill=YELLOW,stroke="none")
    core_p=ellipse(y=13,w=2.5,h=5,fill=WHITE,stroke="none")
    return outer_p+mid_p+inner_p+core_p
small=small_petal()|rotate(25)|repeat(8,rotate(45))
center_dot=circle(r=6,fill=YELLOW,stroke="none")+circle(r=2.5,fill=MAROON,stroke="none")
middle=outter+octagon+small+lines1+lines2+center_dot
show(middle)

pookalam=background+diyas+green_circle+outer_ring+outer_ring1+inner+outer_layer+yellow_ring+layer1+inner_rectangle+inner_rectangle1+octagon+large+center_green+rectangle1+rectangle2+rectangle3+rectangle4+rectangle5+rectangle6+rectangle7+rectangle8+r+middle
show(pookalam)